### ISSUE TITLE
Broken first build

### ISSUE THREAD

**Issue by rkrejci** [CESNET/Nemea#15]
When the tools are being built for the first time and configure scripts are running, the configure script of nemea-supervisor misses libtrap which is included in other part of the project.
```
=== configuring in nemea-supervisor (/home/krejci/workspace/nemea/nemea-supervisor)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local'  '--sysconfdir=/etc/nemea' --cache-file=/dev/null --srcdir=.
...
configure: error: Package requirements (libtrap) were not met:

No package 'libtrap' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libtrap_CFLAGS
and libtrap_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
configure: error: ./configure failed for nemea-supervisor
```
Here is the complete log: [configure.log](https://github.com/CESNET/Nemea/files/2420953/configure.log)

**Comment by rkrejci** [comment]
Another issue is that the configure's `--disable-supervisor` option does not work. The nemea-supervisor is being configured even with this option, so it cannot be used to bypass the dpendency problem.

**Comment by cejkato2** [comment]
Hello Radek,
when You want to compile the whole nemea repo without previously installed `nemea-framework`, You should add `--enable-repobuild` option that "skips" default pkg-config checks.
I've checked README and it's luckily there: https://github.com/CESNET/Nemea#source-codes

To the https://github.com/CESNET/Nemea/issues/15#issuecomment-424812967 comment: well, You are right, `configure` is started anyway... I'm afraid it's a feature of autotools... (but maybe it can be hacked somehow) The `--disable-supervisor` option was added in order to skip entering nemea-supervisor/ by `make` process.
So, this option "works" but the effect is observable after `configure`, i.e., during `make` phase.

Is this explanation fine?
Tomas
